name: 🚀 Deploy Website
on:
  push:
    branches:
      - main  # Look at the bottom of your VS Code window. If it says 'master' instead of 'main', change this to 'master'
jobs:
  web-deploy:
    name: 🎉 Build and Sync
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: ⚙️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 🔨 Install & Build Frontend
      run: |
        cd client
        npm install
        npm run build
    
    - name: 📂 Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./client/dist/
        server-dir: ./
        